spring.application.name=todo-app

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/todoapp}

spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:Yakumu87}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


#===============================
# JPA / HIBERNATE
#===============================
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show_sql=true
spring.jpa.properties.hibernate.format_sql=true

#codificacion de los archivos 
server.servlet.encoding.charset=UTF-8

logging.level.org.springframework.security=DEBUG


server.forward-headers-strategy=framework